export const categoryData = [
  {
    id: 1,
    value: "⁠Boiler",
    label: "⁠Boiler",
    status: "active",
    createdAt: "28 Aug 2024",
    updatedAt: "",
  },
  {
    id: 2,
    value: "⁠⁠Pressure Vessel",
    label: "⁠⁠Pressure Vessel",
    status: "active",
    createdAt: "28 Aug 2024",
    updatedAt: "",
  },
  {
    id: 3,
    value: "⁠Lifting Equipment (Elevating Devices)",
    label: "⁠Lifting Equipment (Elevating Devices)",
    status: "active",
    createdAt: "28 Aug 2024",
    updatedAt: "",
  },
  {
    id: 4,
    value: "⁠Competences - Boiler and Pressure Vessels",
    label: "⁠Competences - Boiler and Pressure Vessels",
    status: "active",
    createdAt: "28 Aug 2024",
    updatedAt: "",
  },
  {
    id: 5,
    value: "⁠Competences - Lifting Equipment & Lifting Operation",
    label: "⁠Competences - Lifting Equipment & Lifting Operation",
    status: "active",
    createdAt: "28 Aug 2024",
    updatedAt: "",
  },
  {
    id: 6,
    value:
      "⁠⁠Authorization for Organizations, Contractors & Service Providers (Boiler & Pressure Vessels)",
    label:
      "⁠⁠Authorization for Organizations, Contractors & Service Providers (Boiler & Pressure Vessels)",
    status: "active",
    createdAt: "28 Aug 2024",
    updatedAt: "",
  },
  {
    id: 7,
    value:
      "⁠Authorization for Organizations, Contractors & Service Providers (Lifting Equipment)",
    label:
      "⁠Authorization for Organizations, Contractors & Service Providers (Lifting Equipment)",
    status: "active",
    createdAt: "28 Aug 2024",
    updatedAt: "",
  },
  {
    id: 8,
    value: "⁠⁠Certification - Boiler, Pressure Vessels & Lifting Equipment ",
    label: "⁠⁠Certification - Boiler, Pressure Vessels & Lifting Equipment ",
    status: "active",
    createdAt: "28 Aug 2024",
    updatedAt: "",
  },
  {
    id: 9,
    value: "⁠Document Review- Boiler & Pressure Vessels ",
    label: "⁠Document Review- Boiler & Pressure Vessels ",
    status: "active",
    createdAt: "28 Aug 2024",
    updatedAt: "",
  },
  {
    id: 10,
    value: "⁠⁠Document Review - Lifting Equipment & Elevating Devices",
    label: "⁠⁠Document Review - Lifting Equipment & Elevating Devices",
    status: "active",
    createdAt: "28 Aug 2024",
    updatedAt: "",
  },
  {
    id: 11,
    value:
      "Personnel, Test, Qualification and Validation (Boiler, Pressure Vessels)",
    label:
      "Personnel, Test, Qualification and Validation (Boiler, Pressure Vessels)",
    status: "active",
    createdAt: "28 Aug 2024",
    updatedAt: "",
  },
  {
    id: 12,
    value: "Personnel, Test, Qualification and Validation (Lifting Equipment)",
    label: "Personnel, Test, Qualification and Validation (Lifting Equipment)",
    status: "active",
    createdAt: "28 Aug 2024",
    updatedAt: "",
  },
  {
    id: 13,
    value: "Authorization for Organization, Contractors & Services Providers",
    label: "Authorization for Organization, Contractors & Services Providers",
    status: "active",
    createdAt: "21 Aug 2024",
    updatedAt: "28 Aug 2024",
  },
];
